### ISSUE TITLE
How to handle Node versioning?

### ISSUE THREAD

**Issue by georgemandis** [georgemandis/101-hello-worlds#14]
One of the solutions works in v11.4.0 but not other versions of Node. I blame my own lack of diligence.

Still, it raises an interesting question. I've got a GitHub action running the tests now. Should I pick a version of Node that all the solutions have to work under and stick with that? Should I explore a fancier fix where each solution can post something like it's own `.nvmrc` file and modify the tests to use the requests version of Node?

Decisions decisions...

**Comment by nderscore** [comment]
Being on the bleeding edge of new language features will allow for more unique solutions, so it would be great if it could be kept up to date. 

Dealing with managing node versions in order to run the tests sounds like a pain, though.

Since none of the solutions have been broken by a new version of node yet, I don't see why running CI tests on the latest version of node for the time being would be a problem. Cross that bridge if/when you get there? 😄

**Comment by georgemandis** [comment]
I agree bleeding edge features expand the possibilities. 

The challenge here is that one of them *only* passes in Node 11.4.0 right now... and it’s one I contributed! I know why, but I’m sort of at a loss as to how to refactor it, mostly because it’s obnoxiously obfuscated and the only way I can think to fix it would give away some of the fun :)

**Comment by georgemandis** [comment]
It’s 023, just FYI.

**Comment by georgemandis** [comment]
Closing because #25 is more direct and actionable.
